#!/bin/bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Start Nginx
service nginx start

# Create a custom HTML page
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure Nginx is listening on port 80
ufw allow 'Nginx HTTP'

# Restart Nginx without using systemctl
service nginx restart

